Repository teamulster2/soTired, pull requests merged in 2021-09, with the labels that each got.

#35 [issue/15] - created go setup for a cli
  server/cmd/go.mod
  server/cmd/go.sum
  server/cmd/root.go
  server/go.mod
  server/go.sum
  server/main.go
Labels: enhancement

#46 issue/33 make go installation
  .gitignore
  .hooks/pre-commit
  Makefile
  makefile
Labels: enhancement

#47 [issue/28] - added server pipeline
  .github/workflows/main.yml
  README.md
Labels: enhancement

#50 Issue/49 - Improve flutter analyze rules
  app/analysis_options.yaml
  app/lib/main.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/widget_test.dart
Labels: enhancement

#45 Issue/20 - Implement config manager
  .github/workflows/main.yml
  .hooks/pre-commit
  Makefile
  app/android/app_android.iml
  app/android/local.properties
  app/lib/config/client_config.dart
  app/lib/config/config.dart
  app/lib/config/config_manager.dart
  app/lib/config/config_utils.dart
  app/lib/main.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/config_test.dart
  app/test/widget_test.dart
Labels: enhancement

#44 Issue/4 draw mockups
  app/assets/images/background_06.png
  app/lib/main.dart
  app/lib/ui/constants/constants.dart
  app/lib/ui/core/home/home.dart
  app/lib/ui/core/home/widgets/home_button.dart
  app/lib/ui/core/home/widgets/home_image.dart
  app/lib/ui/core/navigation/navigation.dart
  app/lib/ui/core/navigation/navigation_drawer.dart
  app/lib/ui/models/questionnaire.dart
  app/lib/ui/modules/questionnaire/questionnaire.dart
  app/lib/ui/modules/questionnaire/widgets/questionnaire_answer.dart
  app/lib/ui/modules/questionnaire/widgets/questionnaire_progress.dart
  app/lib/ui/modules/questionnaire/widgets/questionnaire_question.dart
  app/lib/ui/modules/twoSidesTest/two_sides_test.dart
  app/lib/ui/modules/twoSidesTest/widgets/down_previews.dart
  app/lib/ui/modules/twoSidesTest/widgets/left_previews.dart
  app/lib/ui/modules/twoSidesTest/widgets/plain_previews.dart
  app/lib/ui/modules/twoSidesTest/widgets/preview_container.dart
  app/lib/ui/modules/twoSidesTest/widgets/right_previews.dart
  app/lib/ui/modules/twoSidesTest/widgets/up_previews.dart
  app/pubspec.yaml
Labels: enhancement

#52 [issue/17] - Changes in questionnaire and config
  app/lib/config/client_config.dart
  app/lib/config/config_manager.dart
  app/lib/main.dart
  app/lib/ui/core/home/widgets/home_button.dart
  app/lib/ui/modules/questionnaire/questionnaire.dart
  app/test/config_test.dart
Labels: enhancement

#53 [issue/39] - Added logo
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/icon/icon.png
  app/ios/Runner.xcodeproj/project.pbxproj
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  app/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement

#58 Issue/18 notifications
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/res/drawable/icon.png
  app/lib/config/config_manager.dart
  app/lib/main.dart
  app/lib/notification.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/config_test.dart
Labels: enhancement

#62 Issue/57 spatial span task
  app/lib/notification.dart
  app/lib/ui/core/home/home.dart
  app/lib/ui/models/exceptions.dart
  app/lib/ui/modules/spatial_span_test/engine/game_engine.dart
  app/lib/ui/modules/spatial_span_test/engine/game_state.dart
  app/lib/ui/modules/spatial_span_test/spatial_span_test.dart
  app/lib/ui/modules/spatial_span_test/widgets/spatial_span_test_box.dart
  app/lib/ui/modules/spatial_span_test/widgets/spatial_span_test_progress.dart
Labels: enhancement

#67 [issue/22] - Fix issue
  app/lib/config/client_config.dart
  app/lib/config/config_manager.dart
  app/lib/database/database_manager.dart
  app/lib/database/models/questionnaire/questionnaire_answers.dart
  app/lib/database/models/score/personal_high_score.dart
  app/lib/database/models/user/user_access_method.dart
  app/lib/database/models/user/user_state.dart
  app/lib/database/models/user/user_state.g.dart
  app/lib/ui/modules/twoSidesTest/widgets/down_previews.dart
  app/lib/ui/modules/twoSidesTest/widgets/left_previews.dart
  app/lib/ui/modules/twoSidesTest/widgets/plain_previews.dart
  app/lib/ui/modules/twoSidesTest/widgets/right_previews.dart
  app/lib/ui/modules/twoSidesTest/widgets/up_previews.dart
  app/lib/utils.dart
  app/test/config_manager_test.dart
Labels: bug, enhancement

#71 Issue/70 scheduler notification
  app/lib/config/client_config.dart
  app/lib/config/config_manager.dart
  app/lib/notifications.dart
  app/lib/service_provider.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/config_manager_test.dart
Labels: enhancement

#73 Issue/25 - Add export functionality, issue/51 - Add exception handling
  .github/workflows/main.yml
  .hooks/pre-commit
  Makefile
  app/analysis_options.yaml
  app/lib/config/client_config.dart
  app/lib/config/config_manager.dart
  app/lib/database/database_manager.dart
  app/lib/database/models/module_type.dart
  app/lib/database/models/module_type.g.dart
  app/lib/database/models/questionnaire/questionnaire_answers.dart
  app/lib/database/models/questionnaire/questionnaire_answers.g.dart
  app/lib/database/models/questionnaire/questionnaire_result.dart
  app/lib/database/models/questionnaire/questionnaire_result.g.dart
  app/lib/database/models/score/personal_high_score.dart
  app/lib/database/models/user/user_access_method.dart
  app/lib/database/models/user/user_access_method.g.dart
  app/lib/database/models/user/user_log.dart
  app/lib/database/models/user/user_log.g.dart
  app/lib/database/models/user/user_state.dart
  app/lib/exceptions/exceptions.dart
  app/lib/main.dart
  app/lib/notifications/notifications.dart
  app/lib/service_provider/service_provider.dart
  app/lib/ui/models/questionnaire.dart
  app/lib/ui/modules/questionnaire/questionnaire.dart
  app/lib/utils/utils.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/config_manager_test.dart
  app/test/database_manager_test.dart
  app/test/database_manager_test.mocks.dart
Labels: bug, enhancement

#74 Issue/66 app loading screen
  app/assets/images/angry.png
  app/assets/images/boring.png
  app/assets/images/exiting.png
  app/assets/images/happy.png
  app/assets/images/happy2.png
  app/assets/images/happy3.png
  app/assets/images/happy4.png
  app/lib/main.dart
  app/lib/ui/constants/constants.dart
  app/lib/ui/core/home/home.dart
  app/lib/ui/core/home/widgets/home_button.dart
  app/lib/ui/core/home/widgets/home_image.dart
  app/lib/ui/models/dialog_objects.dart
  app/lib/ui/models/exceptions.dart
  app/lib/ui/models/questionnaire.dart
  app/lib/ui/modules/pvt_test/pvt_test.dart
  app/lib/ui/modules/pvt_test/widgets/pvt_test_diff.dart
  app/lib/ui/modules/pvt_test/widgets/pvt_test_progress.dart
  app/lib/ui/modules/pvt_test/widgets/pvt_test_square.dart
  app/lib/ui/modules/questionnaire/questionnaire.dart
  app/lib/ui/modules/questionnaire/widgets/questionnaire_answer.dart
  app/lib/ui/modules/questionnaire/widgets/questionnaire_progress.dart
  app/lib/ui/modules/questionnaire/widgets/questionnaire_question.dart
  app/lib/ui/modules/self_assessment/self_assessment.dart
  app/lib/ui/modules/self_assessment/widgets/current_activity.dart
  app/lib/ui/modules/self_assessment/widgets/current_emotional_state.dart
  app/lib/ui/modules/self_test_engine/self_test.dart
  app/lib/ui/modules/self_test_engine/self_test_engine.dart
  app/lib/ui/modules/self_test_engine/self_test_state.dart
  app/lib/ui/modules/spatial_span_test/engine/game_engine.dart
  app/lib/ui/modules/spatial_span_test/engine/game_state.dart
  app/lib/ui/modules/spatial_span_test/spatial_span_test.dart
  app/lib/ui/modules/spatial_span_test/widgets/spatial_span_test_box.dart
  app/lib/ui/modules/spatial_span_test/widgets/spatial_span_test_progress.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement

#79 Issue/59 - Beautify / Enhance source code
  README.md
  app/android/app/build.gradle
  app/android/app/src/debug/AndroidManifest.xml
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/kotlin/com/soTired/app/MainActivity.kt
  app/android/app/src/profile/AndroidManifest.xml
  app/ios/Runner.xcodeproj/project.pbxproj
  app/ios/Runner/Info.plist
  app/lib/config/client_config.dart
  app/lib/config/config_manager.dart
  app/lib/exceptions/exceptions.dart
  app/lib/main.dart
  app/lib/notifications/notifications.dart
  app/lib/utils/utils.dart
  app/test/config_manager_test.dart
  app/test/database_manager_test.dart
  app/test/utils_test.dart
Labels: bug, enhancement

#83 Issue/21 server database
  Makefile
  server/cmd/go.mod
  server/cmd/go.sum
  server/cmd/models.go
  server/cmd/models_test.go
  server/cmd/root.go
  server/go.mod
  server/go.sum
Labels: enhancement

#81 Issue/72 - Remove moods from config
  README.md
  app/lib/config/client_config.dart
  app/lib/config/config_manager.dart
  app/lib/database/models/user/user_state.dart
  app/lib/database/models/user/user_state.g.dart
  app/lib/exceptions/exceptions.dart
  app/lib/ui/modules/self_assessment/self_assessment.dart
  app/lib/ui/modules/self_assessment/widgets/current_activity.dart
  app/lib/ui/modules/spatial_span_test/spatial_span_test.dart
  app/pubspec.lock
  app/test/config_manager_test.dart
  app/test/database_manager_test.dart
Labels: bug, enhancement

#86 Issue/63 http server
  server/cmd/go.mod
  server/cmd/root.go
  server/cmd/server.go
  server/config.json
  server/go.mod
Labels: enhancement

#88 [issue/87] - Updated study model
  server/cmd/models.go
Labels: bug

#89 Issue/64 http client
  app/android/app/src/main/AndroidManifest.xml
  app/lib/api/client.dart
  app/lib/config/config_manager.dart
  app/lib/exceptions/exceptions.dart
  app/lib/service_provider/service_provider.dart
  app/lib/ui/modules/spatial_span_test/spatial_span_test.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/config_manager_test.dart
  app/test/database_manager_test.mocks.dart
Labels: enhancement

#91 issue/24 server export functionality
  server/cmd/export.go
  server/cmd/export_test.go
  server/cmd/go.mod
  server/cmd/go.sum
  server/cmd/root.go
  server/go.mod
  server/go.sum
Labels: enhancement

#93 Issue/78 implement settings
  README.md
  app/lib/api/client.dart
  app/lib/config/client_config.dart
  app/lib/config/config_manager.dart
  app/lib/database/database_manager.dart
  app/lib/database/models/settings/settings_object.dart
  app/lib/database/models/settings/settings_object.g.dart
  app/lib/main.dart
  app/lib/service_provider/service_provider.dart
  app/lib/ui/core/home/home.dart
  app/lib/ui/core/navigation/navigation.dart
  app/lib/ui/core/widgets/classic_button.dart
  app/lib/ui/modules/questionnaire/questionnaire.dart
  app/lib/ui/modules/self_test_engine/self_test.dart
  app/lib/ui/modules/self_test_engine/self_test_engine.dart
  app/lib/ui/modules/self_test_engine/self_test_state.dart
  app/lib/ui/modules/settings/settings.dart
  app/lib/utils/utils.dart
  app/test/config_manager_test.dart
  app/test/database_manager_test.dart
  app/test/database_manager_test.mocks.dart
Labels: bug, enhancement

#98 Issue/63 http server
  .gitignore
  server/cmd/export.go
  server/cmd/models.go
  server/cmd/models_test.go
  server/cmd/root.go
  server/cmd/server.go
  server/cmd/server_test.go
  server/config.json
Labels: enhancement

#99 [issue/96] - Add global app exception handling
  app/lib/exceptions/exceptions.dart
  app/lib/main.dart
  app/lib/ui/modules/settings/settings.dart
Labels: enhancement

#104 Bug fixes
  app/lib/ui/core/home/home.dart
  app/lib/ui/core/home/widgets/home_image.dart
  app/lib/ui/core/navigation/navigation.dart
  app/lib/ui/modules/pvt_test/pvt_test.dart
  app/lib/ui/modules/pvt_test/widgets/pvt_test_diff.dart
  app/lib/ui/modules/questionnaire/questionnaire.dart
  app/lib/ui/modules/questionnaire/widgets/questionnaire_answer.dart
  app/lib/ui/modules/questionnaire/widgets/questionnaire_progress.dart
  app/lib/ui/modules/self_test_engine/self_test.dart
  app/lib/ui/modules/self_test_engine/self_test_state.dart
  app/lib/ui/modules/settings/settings.dart
  app/lib/ui/modules/spatial_span_test/engine/game_state.dart
  app/lib/ui/modules/spatial_span_test/spatial_span_test.dart
  app/lib/ui/modules/twoSidesTest/two_sides_test.dart
Labels: bug, enhancement

#107 Issue/97 - change database json, issue/105 - fix database export bugs
  app/analysis_options.yaml
  app/lib/api/client.dart
  app/lib/database/database_manager.dart
  app/lib/database/models/module_type.dart
  app/lib/database/models/module_type.g.dart
  app/lib/database/models/settings/settings_object.dart
  app/lib/database/models/settings/settings_object.g.dart
  app/lib/generated_plugin_registrant.dart
  app/lib/service_provider/service_provider.dart
  app/lib/ui/core/home/home.dart
  app/lib/ui/core/home/widgets/home_image.dart
  app/lib/ui/modules/pvt_test/pvt_test.dart
  app/lib/ui/modules/questionnaire/questionnaire.dart
  app/lib/ui/modules/self_test_engine/self_test.dart
  app/lib/ui/modules/self_test_engine/self_test_state.dart
  app/lib/ui/modules/settings/settings.dart
  app/lib/ui/modules/spatial_span_test/spatial_span_test.dart
  app/lib/utils/utils.dart
  app/pubspec.lock
  app/pubspec.yaml
  app/test/database_manager_test.dart
  app/test/database_manager_test.mocks.dart
Labels: bug, enhancement

#112 [issue/108] - Add notification by sending successful the database
  app/lib/api/client.dart
  app/lib/notifications/notifications.dart
  app/lib/ui/modules/settings/settings.dart
  app/pubspec.lock
Labels: enhancement

#113 Issue/97 - Adjust database adapter for server
  app/assets/images/angry.png
  app/assets/images/boring.png
  app/assets/images/exiting.png
  app/assets/images/happy.png
  app/assets/images/happy2.png
  app/assets/images/happy3.png
  app/assets/images/happy4.png
  app/lib/api/client.dart
  app/lib/config/client_config.dart
  app/lib/config/config_manager.dart
  app/lib/database/database_manager.dart
  app/lib/database/models/questionnaire/questionnaire_answers.dart
  app/lib/database/models/questionnaire/questionnaire_answers.g.dart
  app/lib/database/models/questionnaire/questionnaire_result.dart
  app/lib/database/models/questionnaire/questionnaire_result.g.dart
  app/lib/database/models/score/personal_high_score.dart
  app/lib/database/models/score/personal_high_score.g.dart
  app/lib/database/models/settings/settings_object.dart
  app/lib/database/models/settings/settings_object.g.dart
  app/lib/database/models/user/user_game_type.dart
  app/lib/database/models/user/user_game_type.g.dart
  app/lib/database/models/user/user_log.dart
  app/lib/database/models/user/user_log.g.dart
  app/lib/database/models/user/user_state.dart
  app/lib/database/models/user/user_state.g.dart
  app/lib/exceptions/exceptions.dart
  app/lib/ui/modules/psychomotor_vigilance_task/psychomotor_vigilance_task.dart
  app/lib/ui/modules/psychomotor_vigilance_task/widgets/psychomotor_vigilance_task_diff.dart
  app/lib/ui/modules/psychomotor_vigilance_task/widgets/psychomotor_vigilance_task_progress.dart
  app/lib/ui/modules/psychomotor_vigilance_task/widgets/psychomotor_vigilance_task_square.dart
  app/lib/ui/modules/questionnaire/questionnaire.dart
  app/lib/ui/modules/self_assessment/self_assessment.dart
  app/lib/ui/modules/self_assessment/widgets/current_activity.dart
  app/lib/ui/modules/self_assessment/widgets/current_mood.dart
  app/lib/ui/modules/self_test_engine/self_test.dart
  app/lib/ui/modules/self_test_engine/self_test_state.dart
  app/lib/ui/modules/settings/settings.dart
  app/lib/ui/modules/spatial_span_test/engine/game_state.dart
  app/lib/ui/modules/spatial_span_test/spatial_span_test.dart
  app/lib/utils/utils.dart
  app/pubspec.lock
  app/test/config_manager_test.dart
  app/test/database_manager_test.dart
  app/test/database_manager_test.mocks.dart
Labels: bug, enhancement
